// Copyright (c) eBPF for Windows contributors
// SPDX-License-Identifier: MIT
#pragma once

/**
 * @file
 * @brief bpf_program_lib - a minimal "LoadLibrary/GetProcAddress for a bpf2c driver".
 *
 * This library lets a host driver dynamically load a driver generated by bpf2c, obtain the
 * address of an eBPF program function exported by that driver via NMR, resolve the downstream
 * helper functions the program calls against a *static* helper registry supplied by the host,
 * and then invoke the eBPF program function like an ordinary C function.
 *
 * Layer 1 scope (this file):
 *   - No maps, no global variables.
 *   - No program-info / hook NMR providers, no hash checking, no eBPF object runtime.
 *   - A single bpf2c program is loaded at a time.
 *
 * The bpf2c driver is the NMR *client*; this library (hosted in the host driver) is the NMR
 * *provider*. The provider uses a caller-supplied NPI id. The bpf2c client must be generated /
 * built with the same NPI id.
 */

#include "cxplat.h"
#include "ebpf_program_types.h"  // For ebpf_program_data_t
#include "ebpf_shared_framework.h"

#include "bpf2c.h"

#include <guiddef.h>

CXPLAT_EXTERN_C_BEGIN

    /**
     * @brief A single entry in the host's static helper registry.
     *
     * This is the "import table": it maps an eBPF helper id (as referenced by the bpf2c program's
     * program_entry.helpers[].helper_id) to the address of the host's implementation of that helper.
     */
    typedef struct _bpf_helper_registry_entry
    {
        uint32_t helper_id;          ///< Helper id referenced by the eBPF program.
        helper_function_t address;   ///< Host implementation of the helper.
    } bpf_helper_registry_entry_t;

    /**
     * @brief A bound, ready-to-call eBPF program.
     *
     * Conceptually the result of LoadLibrary + GetProcAddress + import resolution.
     */
    typedef struct _bpf_loaded_program
    {
        uint64_t (*function)(void* context, const program_runtime_context_t* runtime_context); ///< Program entry point.
        program_runtime_context_t runtime_context; ///< Runtime context passed on every invoke. Owns helper_data.
        helper_function_data_t* helper_data;        ///< Resolved helper addresses (indexed as program references them).
        uint16_t helper_count;                      ///< Number of entries in helper_data.
    } bpf_loaded_program_t;

    /**
     * @brief Register the NMR provider used to discover and bind bpf2c client drivers.
     *
     * @param[in] npi_id The NPI id the bpf2c client drivers register against.
     * @param[in] registry Static helper registry (import table). Must remain valid until terminate.
     * @param[in] registry_count Number of entries in @p registry.
     *
     * @retval STATUS_SUCCESS The provider was registered.
     */
    NTSTATUS
    bpf_program_lib_initiate(
        _In_ const GUID* npi_id,
        _In_reads_(registry_count) bpf_helper_registry_entry_t* registry,
        size_t registry_count);

    
    /**
     * @brief Deregister the NMR provider and free any loaded program state.
     */
    void
    bpf_program_lib_terminate(void);

    /**
     * @brief Get the currently loaded/bound eBPF program, if any.
     *
     * @return Pointer to the loaded program, or NULL if no bpf2c client is bound.
     */
    _Ret_maybenull_ const bpf_loaded_program_t*
    bpf_program_lib_get_loaded_program(void);

    /**
     * @brief Invoke the bound eBPF program function. Null-safe.
     *
     * @param[in] program The loaded program (may be NULL, in which case 0 is returned).
     * @param[in,out] context Program-type-specific context (layout per the shared context descriptor).
     * @return The program's return value, or 0 if @p program is NULL.
     */
    uint64_t
    bpf_program_lib_invoke(_In_opt_ const bpf_loaded_program_t* program, _Inout_ void* context);

CXPLAT_EXTERN_C_END
