// Copyright (c) eBPF for Windows contributors
// SPDX-License-Identifier: MIT

// WDF initialization utility for BPF maps drivers

#define EBPF_FILE_ID EBPF_FILE_ID_MAPS

#include <ntifs.h>
#include <ntddk.h>

// Disable warning 4062 for WDF headers (unhandled enumerator in switch)
#pragma warning(push)
#pragma warning(disable: 4062)
#include <wdf.h>
#pragma warning(pop)

#include "ebpf_tracelog.h"
#include "bpf_maps_driver.h"

NTSTATUS
bpf_maps_wdf_initialize(
    _In_ PDRIVER_OBJECT DriverObject,
    _In_ PUNICODE_STRING RegistryPath,
    _In_ const bpf_maps_wdf_config_t* config,
    _Out_ WDFDEVICE* device_out,
    _Out_ DEVICE_OBJECT** device_object_out)
{
    NTSTATUS status;
    WDF_DRIVER_CONFIG driver_config;
    WDFDRIVER driver = NULL;
    PWDFDEVICE_INIT device_init = NULL;
    WDFDEVICE device = NULL;
    WDF_IO_QUEUE_CONFIG queue_config;
    WDFQUEUE queue = NULL;
    UNICODE_STRING device_name;
    UNICODE_STRING symbolic_link;
    WDF_OBJECT_ATTRIBUTES attributes;

    EBPF_LOG_ENTRY();

    if (config == NULL || device_out == NULL || device_object_out == NULL) {
        return STATUS_INVALID_PARAMETER;
    }

    // Initialize WDF driver
    WDF_DRIVER_CONFIG_INIT(&driver_config, WDF_NO_EVENT_CALLBACK);
    driver_config.DriverInitFlags |= WdfDriverInitNonPnpDriver;
    driver_config.EvtDriverUnload = (PFN_WDF_DRIVER_UNLOAD)config->unload_callback;

    status = WdfDriverCreate(DriverObject, RegistryPath, WDF_NO_OBJECT_ATTRIBUTES, &driver_config, &driver);
    if (!NT_SUCCESS(status)) {
        EBPF_LOG_NTSTATUS_API_FAILURE(
            EBPF_TRACELOG_KEYWORD_API,
            "WdfDriverCreate",
            status);
        goto Done;
    }

    // Allocate device initialization structure
    device_init = WdfControlDeviceInitAllocate(driver, &SDDL_DEVOBJ_SYS_ALL_ADM_ALL);
    if (device_init == NULL) {
        EBPF_LOG_MESSAGE(
            EBPF_TRACELOG_LEVEL_ERROR,
            EBPF_TRACELOG_KEYWORD_API,
            "WdfControlDeviceInitAllocate failed");
        status = STATUS_INSUFFICIENT_RESOURCES;
        goto Done;
    }

    WdfDeviceInitSetDeviceType(device_init, FILE_DEVICE_NULL);
    WdfDeviceInitSetCharacteristics(device_init, FILE_DEVICE_SECURE_OPEN, FALSE);
    WdfDeviceInitSetCharacteristics(device_init, FILE_AUTOGENERATED_DEVICE_NAME, TRUE);

    // Assign device name
    RtlInitUnicodeString(&device_name, config->device_name);
    status = WdfDeviceInitAssignName(device_init, &device_name);
    if (!NT_SUCCESS(status)) {
        EBPF_LOG_NTSTATUS_API_FAILURE(
            EBPF_TRACELOG_KEYWORD_API,
            "WdfDeviceInitAssignName",
            status);
        WdfDeviceInitFree(device_init);
        goto Done;
    }

    // Create device
    WDF_OBJECT_ATTRIBUTES_INIT(&attributes);
    attributes.SynchronizationScope = WdfSynchronizationScopeNone;

    status = WdfDeviceCreate(&device_init, WDF_NO_OBJECT_ATTRIBUTES, &device);
    if (!NT_SUCCESS(status)) {
        EBPF_LOG_NTSTATUS_API_FAILURE(
            EBPF_TRACELOG_KEYWORD_API,
            "WdfDeviceCreate",
            status);
        WdfDeviceInitFree(device_init);
        goto Done;
    }

    // Create symbolic link
    RtlInitUnicodeString(&symbolic_link, config->symbolic_link);
    status = WdfDeviceCreateSymbolicLink(device, &symbolic_link);
    if (!NT_SUCCESS(status)) {
        EBPF_LOG_NTSTATUS_API_FAILURE(
            EBPF_TRACELOG_KEYWORD_API,
            "WdfDeviceCreateSymbolicLink",
            status);
        goto Done;
    }

    // Create I/O queue
    WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&queue_config, WdfIoQueueDispatchSequential);
    queue_config.EvtIoDeviceControl = (PFN_WDF_IO_QUEUE_IO_DEVICE_CONTROL)config->io_device_control_callback;

    status = WdfIoQueueCreate(device, &queue_config, WDF_NO_OBJECT_ATTRIBUTES, &queue);
    if (!NT_SUCCESS(status)) {
        EBPF_LOG_NTSTATUS_API_FAILURE(
            EBPF_TRACELOG_KEYWORD_API,
            "WdfIoQueueCreate",
            status);
        goto Done;
    }

    WdfControlFinishInitializing(device);

    *device_out = device;
    *device_object_out = WdfDeviceWdmGetDeviceObject(device);

    EBPF_LOG_MESSAGE(
        EBPF_TRACELOG_LEVEL_INFO,
        EBPF_TRACELOG_KEYWORD_BASE,
        "BPF Maps WDF initialization succeeded");

Done:
    EBPF_RETURN_NTSTATUS(status);
}
